from tg_bot import DEV_USERS, SUDO_USERS, SUPPORT_USERS, WHITELIST_USERS, client

IMMUNE_USERS = SUDO_USERS + SUPPORT_USERS + WHITELIST_USERS + DEV_USERS

IMMUNE_USERS = (
    list(SUPPORT_USERS) + list(SUPPORT_USERS) + list(WHITELIST_USERS) + list(DEV_USERS)
)
